[package]
name = "bitvaulty-ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
leptos = { version = "0.6", features = ["csr"] }
leptos_meta = "0.6.14"
leptos_router = { version = "0.6.14", features = ["csr"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
cfg-if = "1.0"
gloo-net = { version = "0.6", features = ["http"] }

log = "0.4"
simple_logger = { version = "5.0", optional = true }
console_log = { version = "1", optional = true }
console_error_panic_hook = "0.1.7"

[workspace]
members = ["src-tauri"]
