[package]
name = "bitvaulty-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
cfg-if = "1.0"
gloo-net = { version = "0.6", features = ["http"] }
js-sys = "0.3"
leptos = { version = "0.6", features = ["csr"] }
leptos_meta = "0.6.14"
leptos_router = { version = "0.6.14", features = ["csr"] }
parking_lot = "0.12.3"
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

# Logging
log = "0.4"
simple_logger = { version = "5.0", optional = true }
console_log = { version = "1", optional = true }
console_error_panic_hook = "0.1.7"


bip39 = { version = "2.0.0", features = ["rand"] }
getrandom = { version = "0.2", features = ["js"] }
zeroize = "1.7.0"
javascriptcore-rs-sys = "1.1.1"


[workspace]
members = ["src-tauri"]

[profile.release]
lto = false
