[workspace]
resolver = "2"
default-members = ["bitvault-ui"]
members = [
    "bitvault-ui",     # Current Leptos frontend
    "bitvault-core",   # Security-focused core component
    "bitvault-common", # Shared types and utilities
]

# Workspace-wide settings (shared by all members)
[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["BitVault Team", "Hunter Beast", "Secure Sovereign"]
repository = "https://github.com/BitVaulty/BitVaultWallet"

# Shared dependencies across workspace members
[workspace.dependencies]
# Common dependencies
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1.0.86"
log = "0.4"

# Bitcoin-specific dependencies
bitcoin = "0.30"
bdk = { version = "0.30.2", features = ["keys-bip39", "sqlite"] }

# Security-related dependencies
zeroize = { version = "1.7.0", features = ["derive"] }
getrandom = "0.3.1"
aes-gcm = "0.10.3"
rand = "0.9.0"
rand_core = "0.9.3"
argon2 = "0.5.2"
hex = "0.4.3"

crossbeam-channel = { version = "0.5.8", features = ["std"] }

# Localization dependencies
fluent = "0.15.0"
unic-langid = "0.9.0"

lazy_static = "1.4"

# Add intl-memoizer for localization
intl-memoizer = { version = "0.5.1", features = ["concurrent"] }

[workspace.metadata.test-settings]
test-threads = 1
