services:
  builder:
    build: .
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    environment:
      - CARGO_TERM_COLOR=always
      - RUST_BACKTRACE=1
    ports:
      - "8080:8080"
    command: >
      echo "# Add the wasm32 target for building WebAssembly binaries"
      rustup target add wasm32-unknown-unknown
      rustup target add x86_64-unknown-linux-atk-sys
      rustup target add x86_64-unknown-linux-gnu

      echo "# Build the project for x86_64-unknown-linux-gnu"
      cargo build --target x86_64-unknown-linux-gnu

      echo "# Build the project for wasm32-unknown-unknown"
      cargo build --target wasm32-unknown-unknown
volumes:
  cargo-cache:
  target-cache:
