version: '3.8'

services:
  builder:
    build: .
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/target
    environment:
      - CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu,wasm32-unknown-unknown
      - CARGO_TERM_COLOR=always
      - RUST_BACKTRACE=1
    ports:
      - "8080:8080"
    command: sh -c "rustup target add wasm32-unknown-unknown && cargo build"

volumes:
  cargo-cache:
  target-cache:
