//! UI modules

pub mod address_book;
pub mod advanced_settings;
pub mod components;
pub mod dashboard;
pub mod hardware_wallet;
pub mod help;
pub mod notification_center;
pub mod pin;
pub mod receive;
pub mod recovery;
pub mod secret_notification;
pub mod send_transaction;
pub mod settings;
pub mod subscription;
pub mod transaction_detail;
pub mod vault_creation;
pub mod vault_selection;
