[build]
# Uncomment for default target when developing WASM
# target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
  "--cfg", "getrandom_backend=\"wasm_js\"", "-C", "link-arg=--import-memory",
]

# Ensure consistent feature detection for wasm builds
[unstable]
build-std = ["std", "panic_abort"]