name: Build and Store Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev pkg-config nodejs npm git lld clang

      - name: Install Trunk
        run: cargo install trunk

      - name: Add Rust targets
        run: |
          rustup target add wasm32-unknown-unknown
          rustup target add x86_64-unknown-linux-gnu

      - name: Build project
        run: cargo tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitvaulty
          path: target/x86_64-unknown-linux-gnu/release/bitvaulty

      - name: Test build artifact
        run: |
          ./target/x86_64-unknown-linux-gnu/release/bitvaulty --version